// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: objects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBucketObjects = `-- name: CountBucketObjects :one
SELECT COUNT(*)::BIGINT
FROM core.bucket_objects
WHERE bucket_id = $1
  AND (btrim($2) = '' OR object_key ILIKE '%' || btrim($2) || '%')
`

type CountBucketObjectsParams struct {
	BucketID uuid.UUID `json:"bucket_id"`
	Btrim    string    `json:"btrim"`
}

func (q *Queries) CountBucketObjects(ctx context.Context, arg CountBucketObjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBucketObjects, arg.BucketID, arg.Btrim)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createBucketObject = `-- name: CreateBucketObject :one
INSERT INTO core.bucket_objects (
  bucket_id,
  object_key,
  content_type,
  size_bytes,
  checksum_sha256,
  storage_path,
  uploaded_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bucket_id, object_key, content_type, size_bytes, checksum_sha256, storage_path, uploaded_by_user_id, created_at
`

type CreateBucketObjectParams struct {
	BucketID         uuid.UUID   `json:"bucket_id"`
	ObjectKey        string      `json:"object_key"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	ChecksumSha256   string      `json:"checksum_sha256"`
	StoragePath      string      `json:"storage_path"`
	UploadedByUserID pgtype.UUID `json:"uploaded_by_user_id"`
}

func (q *Queries) CreateBucketObject(ctx context.Context, arg CreateBucketObjectParams) (CoreBucketObject, error) {
	row := q.db.QueryRow(ctx, createBucketObject,
		arg.BucketID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StoragePath,
		arg.UploadedByUserID,
	)
	var i CoreBucketObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StoragePath,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBucketObjectByKey = `-- name: DeleteBucketObjectByKey :one
DELETE FROM core.bucket_objects
WHERE bucket_id = $1
  AND object_key = $2
RETURNING id, bucket_id, object_key, content_type, size_bytes, checksum_sha256, storage_path, uploaded_by_user_id, created_at
`

type DeleteBucketObjectByKeyParams struct {
	BucketID  uuid.UUID `json:"bucket_id"`
	ObjectKey string    `json:"object_key"`
}

func (q *Queries) DeleteBucketObjectByKey(ctx context.Context, arg DeleteBucketObjectByKeyParams) (CoreBucketObject, error) {
	row := q.db.QueryRow(ctx, deleteBucketObjectByKey, arg.BucketID, arg.ObjectKey)
	var i CoreBucketObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StoragePath,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getBucketObjectByKey = `-- name: GetBucketObjectByKey :one
SELECT id, bucket_id, object_key, content_type, size_bytes, checksum_sha256, storage_path, uploaded_by_user_id, created_at FROM core.bucket_objects
WHERE bucket_id = $1
  AND object_key = $2
`

type GetBucketObjectByKeyParams struct {
	BucketID  uuid.UUID `json:"bucket_id"`
	ObjectKey string    `json:"object_key"`
}

func (q *Queries) GetBucketObjectByKey(ctx context.Context, arg GetBucketObjectByKeyParams) (CoreBucketObject, error) {
	row := q.db.QueryRow(ctx, getBucketObjectByKey, arg.BucketID, arg.ObjectKey)
	var i CoreBucketObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StoragePath,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listBucketObjects = `-- name: ListBucketObjects :many
SELECT id, bucket_id, object_key, content_type, size_bytes, checksum_sha256, storage_path, uploaded_by_user_id, created_at FROM core.bucket_objects
WHERE bucket_id = $1
  AND (btrim($2) = '' OR object_key ILIKE '%' || btrim($2) || '%')
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListBucketObjectsParams struct {
	BucketID uuid.UUID `json:"bucket_id"`
	Btrim    string    `json:"btrim"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBucketObjects(ctx context.Context, arg ListBucketObjectsParams) ([]CoreBucketObject, error) {
	rows, err := q.db.Query(ctx, listBucketObjects,
		arg.BucketID,
		arg.Btrim,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreBucketObject
	for rows.Next() {
		var i CoreBucketObject
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StoragePath,
			&i.UploadedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveBucketObject = `-- name: MoveBucketObject :one
UPDATE core.bucket_objects
SET bucket_id = $3,
    object_key = $4,
    storage_path = $5
WHERE bucket_id = $1
  AND object_key = $2
RETURNING id, bucket_id, object_key, content_type, size_bytes, checksum_sha256, storage_path, uploaded_by_user_id, created_at
`

type MoveBucketObjectParams struct {
	BucketID    uuid.UUID `json:"bucket_id"`
	ObjectKey   string    `json:"object_key"`
	BucketID_2  uuid.UUID `json:"bucket_id_2"`
	ObjectKey_2 string    `json:"object_key_2"`
	StoragePath string    `json:"storage_path"`
}

func (q *Queries) MoveBucketObject(ctx context.Context, arg MoveBucketObjectParams) (CoreBucketObject, error) {
	row := q.db.QueryRow(ctx, moveBucketObject,
		arg.BucketID,
		arg.ObjectKey,
		arg.BucketID_2,
		arg.ObjectKey_2,
		arg.StoragePath,
	)
	var i CoreBucketObject
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StoragePath,
		&i.UploadedByUserID,
		&i.CreatedAt,
	)
	return i, err
}
