// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (CoreOrganizationMember, error)
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (CoreProjectMember, error)
	BootstrapOrganization(ctx context.Context, arg BootstrapOrganizationParams) (BootstrapOrganizationRow, error)
	CountAuditLogsForProject(ctx context.Context, arg CountAuditLogsForProjectParams) (int64, error)
	CountBucketObjects(ctx context.Context, arg CountBucketObjectsParams) (int64, error)
	CountDocuments(ctx context.Context, collectionID uuid.UUID) (int64, error)
	CountOrganizationOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountProjectAdmins(ctx context.Context, projectID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CoreApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CoreAuditLog, error)
	CreateBucket(ctx context.Context, arg CreateBucketParams) (CoreBucket, error)
	CreateBucketObject(ctx context.Context, arg CreateBucketObjectParams) (CoreBucketObject, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (CoreCollection, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CoreDocument, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CoreProjectInvitation, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CoreOrganization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CoreProject, error)
	DeleteBucketByID(ctx context.Context, id uuid.UUID) (CoreBucket, error)
	DeleteBucketObjectByKey(ctx context.Context, arg DeleteBucketObjectByKeyParams) (CoreBucketObject, error)
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error
	DeleteOrganizationByID(ctx context.Context, id uuid.UUID) (CoreOrganization, error)
	DeletePendingInvitationByIDForOrganization(ctx context.Context, arg DeletePendingInvitationByIDForOrganizationParams) (CoreProjectInvitation, error)
	DeleteProjectByID(ctx context.Context, id uuid.UUID) (CoreProject, error)
	GetAPIKeyByIDForProject(ctx context.Context, arg GetAPIKeyByIDForProjectParams) (CoreApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	GetBucketByID(ctx context.Context, id uuid.UUID) (GetBucketByIDRow, error)
	GetBucketObjectByKey(ctx context.Context, arg GetBucketObjectByKeyParams) (CoreBucketObject, error)
	GetCollectionByID(ctx context.Context, id uuid.UUID) (CoreCollection, error)
	GetCollectionBySlug(ctx context.Context, arg GetCollectionBySlugParams) (CoreCollection, error)
	GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (CoreDocument, error)
	GetInvitationByIDForOrganization(ctx context.Context, arg GetInvitationByIDForOrganizationParams) (CoreProjectInvitation, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (CoreProjectInvitation, error)
	GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (GetOrganizationMembershipRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (CoreProject, error)
	GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (GetProjectMembershipRow, error)
	GetProjectOverview(ctx context.Context, id uuid.UUID) (GetProjectOverviewRow, error)
	GetUserByAuthSubject(ctx context.Context, authSubject string) (CoreUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (CoreUser, error)
	ListAPIKeysForProject(ctx context.Context, projectID uuid.UUID) ([]CoreApiKey, error)
	ListAuditLogsForProject(ctx context.Context, arg ListAuditLogsForProjectParams) ([]CoreAuditLog, error)
	ListBucketObjects(ctx context.Context, arg ListBucketObjectsParams) ([]CoreBucketObject, error)
	ListBucketsForOrganization(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error)
	ListBucketsForProject(ctx context.Context, arg ListBucketsForProjectParams) ([]CoreBucket, error)
	ListCollections(ctx context.Context, projectID uuid.UUID) ([]CoreCollection, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]CoreDocument, error)
	ListInvitationsForOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListInvitationsForOrganizationRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjectsForOrganization(ctx context.Context, arg ListProjectsForOrganizationParams) ([]ListProjectsForOrganizationRow, error)
	MarkInvitationAccepted(ctx context.Context, id uuid.UUID) (CoreProjectInvitation, error)
	MoveBucketObject(ctx context.Context, arg MoveBucketObjectParams) (CoreBucketObject, error)
	RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) (CoreOrganizationMember, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (CoreProjectMember, error)
	RemoveProjectMembershipsForOrganizationUser(ctx context.Context, arg RemoveProjectMembershipsForOrganizationUserParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (CoreApiKey, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateBucketByID(ctx context.Context, arg UpdateBucketByIDParams) (CoreBucket, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (CoreCollection, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (CoreDocument, error)
	UpdateOrganizationByID(ctx context.Context, arg UpdateOrganizationByIDParams) (CoreOrganization, error)
	UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (CoreOrganizationMember, error)
	UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) (CoreProject, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (CoreProjectMember, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (CoreUser, error)
}

var _ Querier = (*Queries)(nil)
