// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (CoreOrganizationMember, error)
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (CoreProjectMember, error)
	BootstrapOrganization(ctx context.Context, arg BootstrapOrganizationParams) (BootstrapOrganizationRow, error)
	ComponentHealthRows(ctx context.Context, projectID uuid.UUID) ([]ComponentHealthRowsRow, error)
	CountAuditLogsForProject(ctx context.Context, arg CountAuditLogsForProjectParams) (int64, error)
	CountBucketObjects(ctx context.Context, arg CountBucketObjectsParams) (int64, error)
	CountDocuments(ctx context.Context, collectionID uuid.UUID) (int64, error)
	CountOrganizationOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountOrganizations(ctx context.Context) (int64, error)
	CountProjectAdmins(ctx context.Context, projectID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CoreApiKey, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (CoreAlertRule, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (CoreAuditLog, error)
	CreateBucket(ctx context.Context, arg CreateBucketParams) (CoreBucket, error)
	CreateBucketObject(ctx context.Context, arg CreateBucketObjectParams) (CoreBucketObject, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (CoreCollection, error)
	CreateDBConnection(ctx context.Context, arg CreateDBConnectionParams) (CoreDbConnection, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CoreDocument, error)
	CreateInboundHook(ctx context.Context, arg CreateInboundHookParams) (CoreInboundHook, error)
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (CoreIntegration, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CoreProjectInvitation, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CoreOrganization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CoreProject, error)
	CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (CoreScheduledJob, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CoreWebhook, error)
	DeleteAlertRule(ctx context.Context, arg DeleteAlertRuleParams) error
	DeleteBucketByID(ctx context.Context, id uuid.UUID) (CoreBucket, error)
	DeleteBucketObjectByKey(ctx context.Context, arg DeleteBucketObjectByKeyParams) (CoreBucketObject, error)
	DeleteCollection(ctx context.Context, arg DeleteCollectionParams) error
	DeleteComponent(ctx context.Context, arg DeleteComponentParams) error
	DeleteDBConnection(ctx context.Context, arg DeleteDBConnectionParams) (CoreDbConnection, error)
	DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error
	DeleteInboundHook(ctx context.Context, arg DeleteInboundHookParams) error
	DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) (CoreIntegration, error)
	DeleteOrganizationByID(ctx context.Context, id uuid.UUID) (CoreOrganization, error)
	DeletePendingInvitationByIDForOrganization(ctx context.Context, arg DeletePendingInvitationByIDForOrganizationParams) (CoreProjectInvitation, error)
	DeleteProjectByID(ctx context.Context, id uuid.UUID) (CoreProject, error)
	DeleteProjectSecret(ctx context.Context, arg DeleteProjectSecretParams) (uuid.UUID, error)
	DeleteScheduledJob(ctx context.Context, arg DeleteScheduledJobParams) (uuid.UUID, error)
	DeleteSetting(ctx context.Context, key string) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (CoreWebhook, error)
	EventTotals(ctx context.Context, arg EventTotalsParams) (EventTotalsRow, error)
	EventTypeSeries(ctx context.Context, arg EventTypeSeriesParams) ([]EventTypeSeriesRow, error)
	FinishScheduledJobRun(ctx context.Context, arg FinishScheduledJobRunParams) (CoreScheduledJobRun, error)
	GetAPIKeyByIDForProject(ctx context.Context, arg GetAPIKeyByIDForProjectParams) (CoreApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error)
	GetAlertRule(ctx context.Context, arg GetAlertRuleParams) (CoreAlertRule, error)
	GetBucketByID(ctx context.Context, id uuid.UUID) (GetBucketByIDRow, error)
	GetBucketObjectByKey(ctx context.Context, arg GetBucketObjectByKeyParams) (CoreBucketObject, error)
	GetCollectionByID(ctx context.Context, id uuid.UUID) (CoreCollection, error)
	GetCollectionBySlug(ctx context.Context, arg GetCollectionBySlugParams) (CoreCollection, error)
	GetComponentByName(ctx context.Context, arg GetComponentByNameParams) (CoreComponent, error)
	GetDBConnectionByID(ctx context.Context, id uuid.UUID) (CoreDbConnection, error)
	GetDBConnectionByName(ctx context.Context, arg GetDBConnectionByNameParams) (CoreDbConnection, error)
	GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (CoreDocument, error)
	GetInboundHook(ctx context.Context, arg GetInboundHookParams) (CoreInboundHook, error)
	GetInboundHookByToken(ctx context.Context, token string) (CoreInboundHook, error)
	GetIntegrationByID(ctx context.Context, id uuid.UUID) (CoreIntegration, error)
	GetInvitationByIDForOrganization(ctx context.Context, arg GetInvitationByIDForOrganizationParams) (CoreProjectInvitation, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (CoreProjectInvitation, error)
	GetOrganizationMembership(ctx context.Context, arg GetOrganizationMembershipParams) (GetOrganizationMembershipRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (CoreProject, error)
	GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (GetProjectMembershipRow, error)
	GetProjectOverview(ctx context.Context, id uuid.UUID) (GetProjectOverviewRow, error)
	GetProjectSecret(ctx context.Context, arg GetProjectSecretParams) (CoreProjectSecret, error)
	GetScheduledJobByID(ctx context.Context, id uuid.UUID) (CoreScheduledJob, error)
	GetSetting(ctx context.Context, key string) (GetSettingRow, error)
	GetUserByAuthSubject(ctx context.Context, authSubject string) (CoreUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (CoreUser, error)
	GetWebhookByID(ctx context.Context, id uuid.UUID) (CoreWebhook, error)
	GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (CoreWebhookDelivery, error)
	HasFingerprintSeen(ctx context.Context, arg HasFingerprintSeenParams) (bool, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (CoreEvent, error)
	InsertScheduledJobRun(ctx context.Context, arg InsertScheduledJobRunParams) (CoreScheduledJobRun, error)
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (CoreWebhookDelivery, error)
	// Per-component most recent heartbeat — heartbeat_silence detection.
	LastHeartbeats(ctx context.Context, projectID uuid.UUID) ([]LastHeartbeatsRow, error)
	ListAPIKeysForProject(ctx context.Context, projectID uuid.UUID) ([]CoreApiKey, error)
	ListAlertRules(ctx context.Context, projectID uuid.UUID) ([]CoreAlertRule, error)
	ListAuditLogsForProject(ctx context.Context, arg ListAuditLogsForProjectParams) ([]CoreAuditLog, error)
	ListBucketObjects(ctx context.Context, arg ListBucketObjectsParams) ([]CoreBucketObject, error)
	ListBucketsForOrganization(ctx context.Context, organizationID uuid.UUID) ([]uuid.UUID, error)
	ListBucketsForProject(ctx context.Context, arg ListBucketsForProjectParams) ([]CoreBucket, error)
	ListCollections(ctx context.Context, projectID uuid.UUID) ([]CoreCollection, error)
	ListComponents(ctx context.Context, projectID uuid.UUID) ([]CoreComponent, error)
	ListDBConnections(ctx context.Context, projectID uuid.UUID) ([]CoreDbConnection, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]CoreDocument, error)
	ListDueScheduledJobs(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]CoreScheduledJob, error)
	ListEnabledAlertRules(ctx context.Context) ([]CoreAlertRule, error)
	ListErrorGroups(ctx context.Context, arg ListErrorGroupsParams) ([]ListErrorGroupsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListInboundHooks(ctx context.Context, projectID uuid.UUID) ([]CoreInboundHook, error)
	ListIntegrations(ctx context.Context, projectID uuid.UUID) ([]CoreIntegration, error)
	ListInvitationsForOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListInvitationsForOrganizationRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error)
	ListPendingWebhookDeliveries(ctx context.Context, limit int32) ([]CoreWebhookDelivery, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjectSecretValues(ctx context.Context, projectID uuid.UUID) ([]ListProjectSecretValuesRow, error)
	ListProjectSecrets(ctx context.Context, projectID uuid.UUID) ([]ListProjectSecretsRow, error)
	ListProjectsForOrganization(ctx context.Context, arg ListProjectsForOrganizationParams) ([]ListProjectsForOrganizationRow, error)
	ListScheduledJobRuns(ctx context.Context, arg ListScheduledJobRunsParams) ([]CoreScheduledJobRun, error)
	ListScheduledJobs(ctx context.Context, projectID uuid.UUID) ([]CoreScheduledJob, error)
	ListSettings(ctx context.Context) ([]ListSettingsRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]CoreWebhookDelivery, error)
	ListWebhooks(ctx context.Context, projectID uuid.UUID) ([]CoreWebhook, error)
	ListWebhooksForEvent(ctx context.Context, arg ListWebhooksForEventParams) ([]CoreWebhook, error)
	MarkInvitationAccepted(ctx context.Context, id uuid.UUID) (CoreProjectInvitation, error)
	MarkScheduledJobRan(ctx context.Context, arg MarkScheduledJobRanParams) (CoreScheduledJob, error)
	MarkWebhookDelivery(ctx context.Context, arg MarkWebhookDeliveryParams) error
	MetricNames(ctx context.Context, projectID uuid.UUID) ([]string, error)
	MetricSeries(ctx context.Context, arg MetricSeriesParams) ([]MetricSeriesRow, error)
	MoveBucketObject(ctx context.Context, arg MoveBucketObjectParams) (CoreBucketObject, error)
	PruneScheduledJobRuns(ctx context.Context, arg PruneScheduledJobRunsParams) error
	// Per-component error count inside a sliding window — error_spike detection.
	RecentErrorCounts(ctx context.Context, arg RecentErrorCountsParams) ([]RecentErrorCountsRow, error)
	RemoveOrganizationMember(ctx context.Context, arg RemoveOrganizationMemberParams) (CoreOrganizationMember, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (CoreProjectMember, error)
	RemoveProjectMembershipsForOrganizationUser(ctx context.Context, arg RemoveProjectMembershipsForOrganizationUserParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (CoreApiKey, error)
	SetAlertRuleState(ctx context.Context, arg SetAlertRuleStateParams) error
	SweepExpiredAuditLogs(ctx context.Context) (int64, error)
	// Per-project retention sweeps. A retention of 0 days disables the sweep for
	// that stream. Pending webhook deliveries are never swept — they may still be
	// retrying.
	SweepExpiredEvents(ctx context.Context) (int64, error)
	// Org-scoped audit rows (project_id NULL) have no project retention — sweep
	// them on a fixed 365-day floor so they cannot grow unbounded.
	SweepExpiredOrgAuditLogs(ctx context.Context) (int64, error)
	SweepExpiredWebhookDeliveries(ctx context.Context) (int64, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	TouchInboundHook(ctx context.Context, id uuid.UUID) error
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (CoreAlertRule, error)
	UpdateBucketByID(ctx context.Context, arg UpdateBucketByIDParams) (CoreBucket, error)
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (CoreCollection, error)
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (CoreDocument, error)
	UpdateIntegrationHealth(ctx context.Context, arg UpdateIntegrationHealthParams) error
	UpdateOrganizationByID(ctx context.Context, arg UpdateOrganizationByIDParams) (CoreOrganization, error)
	UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (CoreOrganizationMember, error)
	UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) (CoreProject, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (CoreProjectMember, error)
	UpdateScheduledJob(ctx context.Context, arg UpdateScheduledJobParams) (CoreScheduledJob, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (CoreWebhook, error)
	UpsertComponent(ctx context.Context, arg UpsertComponentParams) (CoreComponent, error)
	UpsertProjectSecret(ctx context.Context, arg UpsertProjectSecretParams) (CoreProjectSecret, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (CoreSetting, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (CoreUser, error)
}

var _ Querier = (*Queries)(nil)
