// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM core.settings WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT key, value, secret, updated_at FROM core.settings WHERE key = $1
`

type GetSettingRow struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	Secret    bool               `json:"secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSetting(ctx context.Context, key string) (GetSettingRow, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i GetSettingRow
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Secret,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, secret, updated_at FROM core.settings ORDER BY key
`

type ListSettingsRow struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	Secret    bool               `json:"secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettingsRow
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Secret,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO core.settings (key, value, secret, updated_by)
VALUES ($1, $2::jsonb, $3, $4)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    secret = EXCLUDED.secret,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING key, value, secret, updated_by, updated_at
`

type UpsertSettingParams struct {
	Key       string  `json:"key"`
	Column2   []byte  `json:"column_2"`
	Secret    bool    `json:"secret"`
	UpdatedBy *string `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (CoreSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting,
		arg.Key,
		arg.Column2,
		arg.Secret,
		arg.UpdatedBy,
	)
	var i CoreSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Secret,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
